apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: decrypt
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       decrypt
  updatePolicy:
    updateMode: "Auto"

