apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: firewall
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       firewall
  updatePolicy:
    updateMode: "Auto"

