apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: proxy
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       proxy
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: 'proxy'
        controlledResources: ["cpu", "memory"]

