apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: decrypt
  name: decrypt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decrypt
  strategy: {}
  template:
    metadata:
      labels:
        app: decrypt
    spec:
      containers:
        - env:
            - name: CHACHA20_KEY
              value: "12345678901234567890123456789012"
          image: jamilakassem/socks-chaining_decrypt
          name: decrypt
          resources: 
            limits:
              cpu: 200m
            requests:
              cpu: 100m
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: decrypt
spec:
  type: NodePort
  selector:
    app: decrypt
  ports:
    - port: 1080
      targetPort: 1080
      nodePort: 30010
      protocol: TCP

