apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: socat
  name: socat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socat
  strategy: {}
  template:
    metadata:
      labels:
        app: socat
    spec:
      containers:
        - image: jamilakassem/socks-chaining_iperf
          name: socat
          securityContext:
            privileged: true
          ports:
            - containerPort: 12345
          resources: 
            limits:
              cpu: 200m
            requests:
              cpu: 100m
      restartPolicy: Always
status: {}


---

apiVersion: v1
kind: Service
metadata:
  name: socat
spec:
  type: NodePort
  selector:
    app: socat
  ports:
    - port: 12345
      nodePort: 30020
      protocol: TCP
